name: CI/CD Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  docker-setup:
    runs-on: arc-small
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2 
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Setup Buildx for multi-platform builds

      - name: Build Docker image
        run: |
          docker build -t my-image .  # Build your Docker image with the tag "my-image"

      - name: Run Docker container
        run: |
          docker run --name my-container -d my-image  # Run the container from the image in detached mode

      - name: Verify Docker container is running
        run: |
          docker ps  # List running containers to verify it's running

